//package ua.kpi.mishchenko.monitoringsystem.dto;
//
//public enum Parameters {
//
//    VOLUMES_ELECTRICITY_CONSUMPTION("isVolumesElectricityConsumption"),
//    ELECTRICITY_COSTS,
//    VOLUMES_ELECTRICITY_PRODUCTION,
//    COSTS_ELECTRICITY_PRODUCTION,
//    VOLUMES_THERMAL_ENERGY_PRODUCTION_SALE,
//    VOLUMES_THERMAL_ENERGY_SALES,
//    VOLUMES_THERMAL_ENERGY_CONSUMPTION,
//    HEAT_ENERGY_COSTS_OWN_NEEDS,
//    VOLUMES_GAS_CONSUMPTION,
//    GAS_EXPENSES,
//    VOLUMES_WATER_CONSUMPTION,
//    WATER_COSTS,
//    VOLUMES_COAL_CONSUMPTION,
//    COAL_COSTS,
//    FUEL_OIL_CONSUMPTION_VOLUMES,
//    COSTS_FUEL_OIL,
//    VOLUMES_DIESEL_FUEL_CONSUMPTION,
//    DIESEL_FUEL_COSTS,
//    VOLUMES_GASOLINE_CONSUMPTION,
//    GASOLINE_EXPENSES,
//    VOLUMES_CONSUMPTION_LUBRICANTS,
//    COSTS_LUBRICANTS,
//    DRAINAGE_VOLUMES,
//    DRAINAGE_COSTS,
//    VOLUMES_SOLID_HOUSEHOLD_WASTE,
//    COSTS_DISPOSAL_SOLID_HOUSEHOLD_WASTE,
//    AMBIENT_TEMPERATURE,
//    VOLUMES_PRODUCTION_PRODUCTS_AND_SERVICES,
//    CO_EMISSIONS;
//
//    private String setter;
//    private String getter;
//}
