CREATE TABLE units
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY,
    parent_id BIGINT NOT NULL DEFAULT 0,
    name      VARCHAR(255)
);

ALTER TABLE units
    ADD CONSTRAINT pk_units PRIMARY KEY (id);